version: '3.4'
services:
    ace-db:
        image: mysql:5.7
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_520_ci
        restart: always
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        expose:
            - '3306'
        volumes:
            - ace-db-volume:/var/lib/mysql
            - ./sql:/docker-entrypoint-initdb.d
        hostname: ace-db
        container_name: ace-db-dev
    redis:
        image: redis:latest
        ports:
            - 6379:6379
        restart: always
        hostname: ace-redis
        container_name: ace-redis-dev
    ace:
        build:
            context: .
            dockerfile: Dockerfile.ace-dev
        image: ace-dev:latest
        depends_on:
            - ace-db
        command: /bin/bash -c "/opt/ace/docker/startup/dev.sh > /opt/ace/docker_startup.log 2>&1"
        expose:
            - '8443'
        volumes:
            - .:/opt/ace
            - ace-data-volume:/opt/ace/data
            - ace-home-volume:/home/ace
        hostname: ace
        container_name: ace-dev
        ports:
            - 5000:5000
            - 8443:8443
        cap_add:
            - SYS_PTRACE
volumes:
    ace-data-volume:
        name: ace-data-dev

    ace-db-volume:
        name: ace-db-dev

    ace-home-volume:
        name: ace-home-dev
        
